### ISSUE TITLE
Use the v0.16.0 tag of each ploigos container instead of :latest

### ISSUE THREAD

**Issue by dwinchell** [ploigos/ploigos-jenkins-library#24]
We received feedback from a prospective customer that using the :latest tag of the ploigos container images in our pipeline definitions makes the pipeline definitions brittle. They're right. Let's use specific tags.

Notes:
* We will also have to update the reference apps to make this stick. Let's remove the overrides from the Jenkinsfiles and just use the defaults. These overrides were present so that developers could iterate fast, but developers can re-introduce the overrides.
* Some of the container images have no default in the groovy. Instead the varaibles are set to null with the expectation that the Jenkinsfile will set them. There is an argument for this because it keeps tech-specifics out of the groovy (i.e. you don't have to reference ploigos/ploigos-tool-maven". But, the cost is your Jenkinsfile is less minimal and you have to change in two places as you release container images. Let's set a default tech-specific image and override when the app uses a different tech.

**Comment by itewk** [comment]
i brain dumped my thoughts on this to @dwinchell and am to lazy to brain dump it here. but before anyone runs with this be sure to sync with @dwinchell if his thoughts have changed at all

**Comment by itewk** [comment]
@dwinchell can we close this out now? also this would be something against the jenkins lib and helm charts for tekton not the PSR.
