### ISSUE TITLE
seperate the "default" container from the "jenkins agent / jnlp" container

### ISSUE THREAD

**Issue by itewk** [ploigos/ploigos-jenkins-library#48]
# purpose

there is a use case where someone wants to swap out the container image used for the jenkins agent / jnlp image, such as with one to talk to CloudBees or something. Currently the same image "default" is used for both the JNLP image as well as any steps that just need the ploigos-step-runner.

# resolution

create a new image parameter and container deffintion in the pod spec of all of the workflows for "JENKINS_AGENT", set the default for that to be ploigos jenkins jlp image (though maybe we dont need that any more and can use upstream?), and then set the default for the existing DEFAULT to be the ploigos-base image

**Comment by itewk** [comment]
@cthiel1 if you decide to do this, created an issue for you :)

**Comment by cthiel1** [comment]
Done in my fork, pending testing

**Comment by itewk** [comment]
@cthiel1 do you need help / a place to test?

**Comment by cthiel1** [comment]
@itewk I need a place to test

**Comment by cthiel1** [comment]
Closed by this PR: https://github.com/ploigos/ploigos-jenkins-library/pull/49
