### ISSUE TITLE
add default resource limits and requests to pod defintions

### ISSUE THREAD

**Issue by itewk** [ploigos/ploigos-jenkins-library#52]
# purpose
Add default resource limits and and requests to pod definitions so reference workflows work in environments with quotas.

# implementation
we should have "sane" defaults, but also make them a parameter that can be overwritten.

# related
* same change for tekton - https://github.com/ploigos/ploigos-charts/issues/17

**Comment by cmasonrh** [comment]
@itewk I'm working on this if you want to assign it to me. Should be ready to PR today.

**Comment by cthiel1** [comment]
Hey @cmasonrh ian is out on PTO through Jan. I assigned you!
